trigger:
- features/*
- main


variables: 
  azureSubscription: 'thundercats-sp'
  appName: 'thundercatscontainer'
  containerRegistry: 'thundercatsregistry'
  dockerRegistryServiceConnection: 'thundercats-docker-registry'
  imageRepository: 'thundercatsfe'
  dockerfilePath: '$(Build.SourcesDirectory)/ThunderCats.Web/Dockerfile'
  tag: '$(Build.BuildId)'
  resourceGroupName: 'thundercats'

  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

  vmImageName: 'ubuntu-latest'

stages:
- stage: BuildStage
  jobs:
  - job: BuildJob
    displayName: Build and Publish to ACR
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)

    - task: Docker@2
      displayName: Build and Push
      inputs:
        repository: $(imageRepository)
        command: 'buildAndPush'
        Dockerfile: $(dockerfilePath)
        tags: '$(tag)'

- stage: deployToDevStage
  jobs:
    - deployment: DeployToDev
      displayName: Deploy To Dev Env
      environment: thundercatscontainerdev_env
      pool:
        vmImage: $(vmImageName)
      strategy:
        runOnce:

          deploy:
            steps:
              - bash: tree
                displayName: Where Am I
                workingDirectory: $(Agent.BuildDirectory)

              - task: AzureWebAppContainer@1
                displayName: 'Azure Web App on Container Deploy'
                inputs:
                  azureSubscription: $(azureSubscription)
                  appName: $(appName)
                  imageName: $(containerRegistry)/$(imageRepository):$(tag)
                  deployToSlotOrASE: true
                  resourceGroupName: $(resourceGroupName)
                  slotName: dev

              
- stage: deployToProd
  # condition: and(succeeded(), eq(variables.isMain, 'true'))
  dependsOn: deployToDevStage
  jobs:
    - deployment: webDeployToProd
      displayName: Deploy To Prod Env
      environment: thundercatscontainerprod_env
      pool:
        vmImage: $(vmImageName)
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureWebAppContainer@1
                displayName: 'Azure Web App on Container Deploy'
                inputs:
                  azureSubscription: $(azureSubscription)
                  appName: $(appName)
                  imageName: $(containerRegistry)/$(imageRepository):$(tag)
                  deployToSlotOrASE: true
                  resourceGroupName: $(resourceGroupName)
                  slotName: production